/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cli.App;

/**
 *
 * @author venji
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbpanel = new javax.swing.JPanel();
        dbtitle = new javax.swing.JLabel();
        dbtitlestudent = new javax.swing.JLabel();
        dbcombobox = new javax.swing.JComboBox<>();
        dbenterbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dbpanel.setBackground(new java.awt.Color(60, 60, 60));

        dbtitle.setFont(new java.awt.Font("72 Black", 1, 26)); // NOI18N
        dbtitle.setForeground(new java.awt.Color(255, 255, 255));
        dbtitle.setText("Malaysia Vaccination Visualizer");

        dbtitlestudent.setFont(new java.awt.Font("72 Black", 1, 22)); // NOI18N
        dbtitlestudent.setForeground(new java.awt.Color(255, 255, 255));
        dbtitlestudent.setText("-Khoo Ven Jin TP051207-");

        dbcombobox.setFont(new java.awt.Font("72 Black", 1, 16)); // NOI18N
        dbcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Statistic Page", "Prolog" }));

        dbenterbtn.setFont(new java.awt.Font("72 Black", 1, 16)); // NOI18N
        dbenterbtn.setText("Enter");
        dbenterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbenterbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dbpanelLayout = new javax.swing.GroupLayout(dbpanel);
        dbpanel.setLayout(dbpanelLayout);
        dbpanelLayout.setHorizontalGroup(
            dbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbpanelLayout.createSequentialGroup()
                .addGroup(dbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbpanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(dbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbtitle)
                            .addGroup(dbpanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(dbcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(dbenterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dbpanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(dbtitlestudent)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        dbpanelLayout.setVerticalGroup(
            dbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(dbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbtitlestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(dbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbenterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbenterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbenterbtnActionPerformed
        int selection = dbcombobox.getSelectedIndex();
        switch(selection){
            case 0: {
                this.setVisible(false);
                new StatisticPage().setVisible(true);
                break;
            }
            case 1: {
                this.setVisible(false);
                new PrologPage().setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_dbenterbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dbcombobox;
    private javax.swing.JButton dbenterbtn;
    private javax.swing.JPanel dbpanel;
    private javax.swing.JLabel dbtitle;
    private javax.swing.JLabel dbtitlestudent;
    // End of variables declaration//GEN-END:variables
}
