/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Font;
import java.util.Arrays;
import java.util.List;
import prolog.PrologStatement;

/**
 *
 * @author venji
 */
public class PrologPage extends javax.swing.JFrame {

    /**
     * Creates new form PrologPage
     */
    public PrologPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        plglogarea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plgpanel = new javax.swing.JPanel();
        plgtitlelabel = new javax.swing.JLabel();
        plgtitlestudent = new javax.swing.JLabel();
        plgsortcombobox = new javax.swing.JComboBox<>();
        plgsortbtn = new javax.swing.JButton();
        plgclearbtn = new javax.swing.JButton();
        plgbackbtn = new javax.swing.JButton();
        plgscrollpane = new javax.swing.JScrollPane();
        plglogarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plgpanel.setBackground(new java.awt.Color(60, 60, 60));

        plgtitlelabel.setFont(new java.awt.Font("72 Black", 1, 26)); // NOI18N
        plgtitlelabel.setForeground(new java.awt.Color(255, 255, 255));
        plgtitlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plgtitlelabel.setText("Malaysia Registration Sorting Prolog");

        plgtitlestudent.setFont(new java.awt.Font("72 Black", 1, 22)); // NOI18N
        plgtitlestudent.setForeground(new java.awt.Color(255, 255, 255));
        plgtitlestudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plgtitlestudent.setText("-Khoo Ven Jin TP051207-");

        plgsortcombobox.setFont(new java.awt.Font("72 Black", 1, 16)); // NOI18N
        plgsortcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total of Vaccination Registration by States in Ascending Order", "Total of Vaccination Registration by States in Descending Order" }));

        plgsortbtn.setFont(new java.awt.Font("72 Black", 1, 16)); // NOI18N
        plgsortbtn.setText("Sort");
        plgsortbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plgsortbtnActionPerformed(evt);
            }
        });

        plgclearbtn.setFont(new java.awt.Font("72 Black", 1, 16)); // NOI18N
        plgclearbtn.setText("Clear Log");
        plgclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plgclearbtnActionPerformed(evt);
            }
        });

        plgbackbtn.setFont(new java.awt.Font("72 Black", 1, 16)); // NOI18N
        plgbackbtn.setText("Go Back");
        plgbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plgbackbtnActionPerformed(evt);
            }
        });

        plglogarea.setColumns(20);
        plglogarea.setRows(5);
        plgscrollpane.setViewportView(plglogarea);

        javax.swing.GroupLayout plgpanelLayout = new javax.swing.GroupLayout(plgpanel);
        plgpanel.setLayout(plgpanelLayout);
        plgpanelLayout.setHorizontalGroup(
            plgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plgpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plgtitlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(plgpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plgtitlestudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(plgpanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(plgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plgscrollpane)
                    .addGroup(plgpanelLayout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(plgclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(plgbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plgpanelLayout.createSequentialGroup()
                        .addComponent(plgsortcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(plgsortbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        plgpanelLayout.setVerticalGroup(
            plgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plgpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(plgtitlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plgtitlestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(plgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plgsortbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plgsortcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(plgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plgbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plgclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(plgscrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plgsortbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plgsortbtnActionPerformed
        String connection = PrologStatement.connectPLFile(PrologStatement.KNOWLEDGEBASE_FILE);
        int selection = plgsortcombobox.getSelectedIndex();
        
        switch(selection){
            case 0: {
                plglogarea.setText("");
                Font bigFont = new Font("calibri", Font.ITALIC, 18);
                plglogarea.setFont(bigFont);
                printOutput(connection + "\n");
                printOutput("-------- [Total of Vaccination Registration by States in Ascending Order] --------");
                
                
                List<String> result = PrologStatement.TotalRegistrationInAscendingOrder();
                result.forEach((tempstring) -> {
                    printOutput(tempstring);
                });
                
                printOutput("____________________________ [End] ____________________________");
                break;
            }
            case 1: {
                plglogarea.setText("");
                Font bigFont = new Font("calibri", Font.ITALIC, 18);
                plglogarea.setFont(bigFont);
                printOutput(connection + "\n");
                printOutput("-------- [Total of Vaccination Registration by States in Descending Order] --------");
                
                List<String> result = PrologStatement.TotalRegistrationInDescendingOrder();
                result.forEach((tempstring) -> {
                    printOutput(tempstring);
                });
                printOutput("____________________________ [End] ____________________________");
                break;
            }
        }
    }//GEN-LAST:event_plgsortbtnActionPerformed

    private void plgclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plgclearbtnActionPerformed
        plglogarea.setText("");
    }//GEN-LAST:event_plgclearbtnActionPerformed

    private void plgbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plgbackbtnActionPerformed
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_plgbackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrologPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrologPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrologPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrologPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrologPage().setVisible(true);
            }
        });
    }
    
    private void printOutput(String message) {
        String currentMessage = plglogarea.getText();
        if (currentMessage.isEmpty()) {
            currentMessage += message;
        } else {
            currentMessage += "\n" + message;
        }
        plglogarea.setText(currentMessage);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton plgbackbtn;
    private javax.swing.JButton plgclearbtn;
    private javax.swing.JTextArea plglogarea;
    private javax.swing.JPanel plgpanel;
    private javax.swing.JScrollPane plgscrollpane;
    private javax.swing.JButton plgsortbtn;
    private javax.swing.JComboBox<String> plgsortcombobox;
    private javax.swing.JLabel plgtitlelabel;
    private javax.swing.JLabel plgtitlestudent;
    // End of variables declaration//GEN-END:variables
}
